# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 14:12
from __future__ import unicode_literals

import book.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn10', models.CharField(blank=True, default='', max_length=10, verbose_name='ISBN10')),
                ('isbn13', models.CharField(max_length=13, validators=[book.models.BookEditValidator.isbn13], verbose_name='ISBN13')),
                ('face_l', models.URLField(blank=True, default='', max_length=255, verbose_name='Face_L')),
                ('face_m', models.URLField(blank=True, default='', max_length=255, verbose_name='Face_M')),
                ('face_s', models.URLField(blank=True, default='', max_length=255, verbose_name='Face_S')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, default='', max_length=128, verbose_name='Subtitle')),
                ('pages', models.PositiveSmallIntegerField(blank=0, default=0, null=0, verbose_name='Pages')),
                ('author', models.CharField(blank=True, default='', max_length=256, verbose_name='Author')),
                ('translator', models.CharField(blank=True, default='', max_length=256, verbose_name='Translator')),
                ('publisher', models.CharField(blank=True, default='', max_length=256, verbose_name='Publisher')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Price')),
                ('binding', models.CharField(blank=True, default='', max_length=128, verbose_name='Binding')),
                ('pubdate', models.DateField(blank=True, help_text='(.etc 2017-11-13)', null=True, verbose_name='Date Published')),
                ('authorDesc', models.TextField(blank=True, default='', verbose_name='Author Desc')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Summary')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Rating')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(help_text='The name of zone', max_length=128, verbose_name='Zone')),
                ('shelf', models.PositiveSmallIntegerField(help_text='The number of shelf', verbose_name='Shelf')),
                ('row', models.PositiveSmallIntegerField(verbose_name='Row')),
                ('col', models.PositiveSmallIntegerField(verbose_name='Col')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readPages', models.PositiveSmallIntegerField(blank=0, default=0, help_text='(Pages Be Read)', null=0, verbose_name='Read Pages')),
                ('readStart', models.DateField(blank=True, help_text='(.etc 2017-11-13)', null=True, verbose_name='Reading Start')),
                ('readEnd', models.DateField(blank=True, help_text='(.etc 2017-11-13)', null=True, verbose_name='Reading Finished')),
                ('readTags', models.TextField(blank=True, default='', verbose_name='Reading Tags')),
                ('readNote', models.TextField(blank=True, default='', verbose_name='Reading Note')),
                ('boughtDate', models.DateField(blank=True, help_text='(.etc 2017-11-13)', null=True, verbose_name='Date Bought')),
                ('boughtPrice', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Price Bought')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader', to='book.Book', verbose_name='Book')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read', to=settings.AUTH_USER_MODEL, verbose_name='Name of Reader')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Location', verbose_name='Location'),
        ),
    ]
